# Generated by Django 5.0.1 on 2024-06-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=444)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('location', models.TextField()),
                ('stats', models.TextField()),
                ('description', models.TextField()),
                ('password', models.CharField(default='raja', max_length=64)),
                ('num_beds', models.PositiveIntegerField(default=0)),
                ('schedule', models.TextField(default='22')),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('total_doctors', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(default='raja@gmail.com', max_length=254)),
                ('image', models.TextField(default='https://www.bing.com/ck/a?!&&p=da0861fa735626ffJmltdHM9MTcxNzM3MjgwMCZpZ3VpZD0xMGVmODQyZC0wNDI0LTZhMmQtMjQwMC05MDU5MDVmNjZiYzMmaW5zaWQ9NTY3Mg&ptn=3&ver=2&hsh=3&fclid=10ef842d-0424-6a2d-2400-905905f66bc3&u=a1L2ltYWdlcy9zZWFyY2g_cT1pbWFnZSZGT1JNPUlRRlJCQSZpZD1GQjQ2NTBGODNCNDhBOEIyNjBGMUVDMUFBODlEQThGRTNFNzFFM0Q0&ntb=1')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialized', models.CharField(choices=[('CR', 'Cardiologist'), ('DR', 'Dermatologist'), ('NR', 'Neurologist')], default='CR', max_length=2)),
                ('description', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=100)),
                ('diabetes', models.BooleanField(default=False)),
                ('prev_stroke', models.DateField(blank=True, null=True)),
                ('cholesterol_level', models.PositiveIntegerField()),
                ('family_ethnicity', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_stats', to='main.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('comments', models.TextField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comments', models.TextField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialists',
            field=models.ManyToManyField(to='main.specialist'),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('location', models.TextField()),
                ('stats', models.TextField()),
                ('description', models.TextField()),
                ('specialists', models.ManyToManyField(to='main.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='main.myuser')),
            ],
        ),
    ]
