# Generated by Django 5.0.1 on 2024-06-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='stats',
            field=models.TextField(null=True),
        ),
    ]
