# Generated by Django 5.0.1 on 2024-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hospital_description_alter_hospital_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
